language: android
android:
        components:
                - build-tools-19.1.0
                - android-19
                - extra-google-google_play_services
                - sys-img-x86-android-17
                - extra
